export class CommonColors {
  buttonColor: Resource = $r('app.color.button_color');
  baseBackgroundGradientStart: Resource = $r('app.color.base_background_gradient_start');
  baseBackgroundGradientEnd: Resource = $r('app.color.base_background_gradient_end');
  menuItem_Background: Resource = $r('app.color.menu_item_background');
  textPrimary: Resource = $r('app.color.text_primary');
  textSecondary: Resource = $r('app.color.text_secondary');
  textOnAccent: Resource = $r('app.color.text_on_accent');
  accent: Resource = $r('app.color.accent');
}